# This is a basic workflow to help you get started with Actions

name: main

env:
  # NO_OF_DAYS: 5
  DAY_OF_WEEK: Monday

# Controls when the workflow will run
on:
  schedule:
    - cron: "1 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - run: mkdir -p ${{ github.workspace }}/artifact
      - run: echo ${{ github.workspace }} 

      - run: echo hello > ${{ github.workspace }}/artifact/world.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ github.workspace }}/artifact/world.txt
          
      - uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/artifact
          
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ${{ github.workspace }}/artifact
        
      - name: Shell script execution
        id: shell-1
        shell: bash
        run: |
             while IFS="," read -r rec_column1 rec_column2 rec_column3 rec_column4
              do
              echo "Displaying Record-$rec_column1"
              echo "Quantity: $rec_column2"
              echo "Price: $rec_column3"
              echo "Value: $rec_column4"
              echo ""
              done < <(tail -n +2 input.csv) 
        env:
          QN_VAR: ${{ vars.rec_column2 }}
          PRICE_VAR: ${{ vars.rec_column3 }}
          VAL_VAR: ${{ vars.rec_column3 }}
        
      - name: checking vairbale
        run: echo "Envrionment variable ${{vars.NO_OF_DAYS}}"
